name: KOTL
main: me.despical.kotl.Main
author: Despical
version: ${project.version}
api-version: 1.13
softdepend: [Multiverse-Core, PlaceholderAPI]

commands:
  kingoftheladder:
    description: KOTL Commands
    aliases: [kotl, kingotladder]

permissions:
  kotl.admin.*:
    default: op
    children:
      kotl.admin: true
      kotl.admin.create: true
      kotl.admin.delete: true
      kotl.admin.edit: true
      kotl.admin.list: true
      kotl.admin.help: true
      kotl.admin.reload: true
