name: KOTL
main: me.despical.kotl.Main
author: Despical
version: ${project.version}
api-version: 1.13
depend: [HolographicDisplays]
softdepend: [PlaceholderAPI]

commands:
  KingOfTheLadder:
    description: King of the Ladder commands
    aliases: [kotl, kingotladder]

permissions:
  kotl.admin.*:
    default: op
    children:
      kotl.command.override: true
      kotl.admin: true
      kotl.admin.edit: true
      kotl.admin.create: true
      kotl.admin.delete: true
      kotl.admin.list: true